jbc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('core.urls')),
    path('produtos/', include('produtos.urls')),
    path('clientes-e-fornecedores/', include('pessoas.urls')),
]

produtos/urls.py
from django.urls import path
from . import views

app_name = 'produtos'
urlpatterns = [
    path('', views.ProdutosList.as_view(), name='listar'),
    path('registrar/', views.ProdutosCreate.as_view(), name='registrar'),
    path('detalhes/<int:pk>/', views.ProdutoDetail.as_view(), name='detalhes'),
    path('detalhes/<int:pk>/excluir/', views.ProdutoRemove.as_view(), name='excluir'),
    #categoria
    path('categoria/', views.CategoriaList.as_view(), name='categoria-listar'),
    path('categoria-registrar/', views.CategoriaCreate.as_view(), name='categoria-registrar'),
    path('categoria-detalhes/<int:pk>/', views.CategoriaDetail.as_view(), name='categoria-detalhes'),
    path('categoria-detalhes/<int:pk>/excluir/', views.CategoriaRemove.as_view(), name='categoria-remover'),
    #marca
    path('marca/', views.MarcaList.as_view(), name='marca-listar'),
    path('marca-registrar/', views.MarcaCreate.as_view(), name='marca-registrar'),
    path('marca-detalhes/<int:pk>/', views.MarcaDetail.as_view(), name='marca-detalhes'),
    path('marca-detalhes/<int:pk>/excluir/', views.MarcaRemove.as_view(), name='marca-remover'),
]

produtos/models.py
from django.db import models
from django.urls import reverse
from pessoas.models import Fornecedor

class Categoria(models.Model):
    nome = models.CharField(max_length=15,
                            unique=True)
    slug = models.SlugField(max_length=100,
                            unique=True)
    fornecedores = models.ManyToManyField(Fornecedor,
                                          related_name='categorias')

    class Meta:
        ordering = ('nome',)
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.nome


class Marca(models.Model):
    nome = models.CharField(max_length=30)
    categoria = models.ForeignKey(Categoria,
                                  related_name='marcas',
                                  null=True,
                                  on_delete=models.SET_NULL)
    slug = models.SlugField(max_length=100)
    fornecedores = models.ManyToManyField(Fornecedor,
                                          related_name='marcas')

    class Meta:
        ordering = ('nome',)
        verbose_name = 'marca'
        verbose_name_plural = 'marcas'


class Produto(models.Model):
    codigo_barras = models.CharField(max_length=14,
                                     db_index=True)
    nome = models.CharField(max_length=100)
    descricacao = models.TextField(verbose_name="descrição",
                                   blank=True)
    custo = models.DecimalField(max_digits=10,
                                decimal_places=2)
    preco = models.DecimalField(verbose_name="preço",
                                max_digits=10,
                                decimal_places=2)
    slug = models.SlugField(max_length=100,
                            db_index=True)
    fornecedores = models.ManyToManyField(Fornecedor,
                                          related_name='produtos')
    categoria = models.ForeignKey(Categoria,
                                  related_name='produtos',
                                  null=True,
                                  on_delete=models.SET_NULL)
    marca = models.ForeignKey(Marca,
                              null=True,
                              on_delete=models.SET_NULL)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)
    disponivel = models.BooleanField(default=True)

    class Meta:
        ordering = ('nome',)
        index_together = (('id', 'codigo_barras', 'slug'),)

    def __str__(self):
        return self.nome.upper()

    def get_absolute_url(self):
        return reverse('produtos:detalhes',
                       args=[self.pk])

produtos/forms.py
from django.forms import ModelForm, widgets
from .models import Categoria, Marca, Produto

class RegistroCategoriaForm(ModelForm):
    class Meta:
        model = Categoria
        exclude = ('slug',)
        widgets = {
            'nome': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nome',
                'id': 'floatingNome',
            }),
            'fornecedores': widgets.SelectMultiple(attrs={
                'class': 'form-control',
                'placeholder': 'Fornecedores',
                'id': 'floatingFornecedor',
            })
        }


class RegistroMarcaForm(ModelForm):
    class Meta:
        model = Marca
        exclude = ('slug',)
        widgets = {
            'nome': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nome',
                'id': 'floatingNome',
            }),
            'categoria': widgets.Select(attrs={
                'class': 'form-control',
                'placeholder': 'Categoria',
                'id': 'floatingCategoria',
            }),
            'fornecedores': widgets.SelectMultiple(attrs={
                'class': 'form-control',
                'placeholder': 'Fornecedores',
                'id': 'floatingFornecedores',
            })
        }


class RegistroProdutosForm(ModelForm):
    class Meta:
        model = Produto
        exclude = ('slug',)
        widgets = {
            'codigo_barras': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Código de Barras',
                'id': 'floatingBarras',
            }),
            'nome': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nome do Produto',
                'id': 'floatingNome',
            }),
            'descricacao': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Descrição do Produto',
                'id': 'floatingDesc',
                'style': 'height: 100px',
            }),
            'custo': widgets.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Custo',
                'id': 'floatingCusto',
            }),
            'preco': widgets.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Preço',
                'id': 'floatingPreco',
            }),
            'categoria': widgets.Select(attrs={
                'class': 'form-select',
                'placeholder': 'Categoria',
                'id': 'floatingCate',
            }),
            'marca': widgets.Select(attrs={
                'class': 'form-select',
                'placeholder': 'Marca',
                'id': 'floatingMarca',
            }),
            'fornecedores': widgets.Select(attrs={
                'class': 'form-select',
                'placeholder': 'Fornecedores',
                'id': 'floatingForn',
            }),
            'disponivel': widgets.CheckboxInput(attrs={
                'class': 'form-check-input',
                'id': 'flexSwDisp',
            })

        }

produtos/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from pessoas import models

from .forms import RegistroCategoriaForm, RegistroMarcaForm, RegistroProdutosForm

from produtos.models import Categoria, Marca, Produto

# CATEGORIA
class CategoriaList(LoginRequiredMixin, ListView):
    model = Categoria
    paginate_by = 50


class CategoriaCreate(LoginRequiredMixin, CreateView):
    template_name = 'produtos/categoria_form.html'
    model = Categoria
    form_class = RegistroCategoriaForm
    success_url = reverse_lazy('produtos:categoria-listar')


class CategoriaDetail(LoginRequiredMixin, UpdateView):
    template_name = 'produtos/categoria_detail.html'
    model = Categoria
    form_class = RegistroCategoriaForm
    success_url = reverse_lazy('produtos:categoria-listar')


class CategoriaRemove(LoginRequiredMixin, DeleteView):
    model = Categoria
    success_url = reverse_lazy('produtos:categoria-listar')


# MARCA
class MarcaList(LoginRequiredMixin, ListView):
    model = Marca
    paginate_by = 50


class MarcaCreate(LoginRequiredMixin, CreateView):
    template_name = 'produtos/marca_form.html'
    model = Marca
    form_class = RegistroMarcaForm
    success_url = reverse_lazy('produtos:marca-listar')


class MarcaDetail(LoginRequiredMixin, UpdateView):
    template_name = 'produtos/marca_detail.html'
    model = Marca
    form_class = RegistroMarcaForm
    success_url = reverse_lazy('produtos:marca-listar')


class MarcaRemove(LoginRequiredMixin, DeleteView):
    model = Marca
    success_url = reverse_lazy('produtos:marca-listar')


# PRODUTO
class ProdutosList(LoginRequiredMixin, ListView):
    model = Produto
    paginate_by = 50


class ProdutosCreate(LoginRequiredMixin, CreateView):
    template_name = 'produtos/produto_form.html'
    model = Produto
    form_class = RegistroProdutosForm
    success_url = reverse_lazy('produtos:listar')


class ProdutoDetail(LoginRequiredMixin, UpdateView):
    model = Produto
    template_name = 'produtos/produto_detail.html'
    form_class = RegistroProdutosForm
    success_url = reverse_lazy('produtos:listar')


class ProdutoRemove(LoginRequiredMixin, DeleteView):
    model = Produto
    success_url = reverse_lazy('produtos:listar')

produtos/templates/produtos/categoria_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Deletar categoria {{ categoria.nome }}{% endblock %}

{% block content %}


<form method="POST">{% csrf_token %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Deseja excluir {{ categoria.nome }}?</h4>
        <p>Cuidado! Ao excluir um item ele não poderá ser recuperado e terá que ser cadastrado novamente</p>
        <hr>
        <p class="mb-0">Clique em <strong>confirmar</strong> para excluir a Categoria.</p>
    </div>
    <input type="submit" class="btn btn-danger" value="Confirmar">
</form>

{% endblock %}

produtos/templates/produtos/categoria_detail.html
{% extends 'base.html' %}

{% block title %}{{ categoria.nome }}{% endblock %}

{% block content %}


<div class="container col-lg-7 p-2">

    <div>
        <h1 class="p-2">Detalhes e atualização</h1>
    </div>

    <form action="{% url 'categoria:detalhes' categoria.id %}" method="POST">{% csrf_token %}
        <div class="row g-3">
            <div class="form-floating mb-3 col-md-6">
                {{ form.nome }}
                <label for="floatingNome">Nome</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.fornecedores }}
                <label for="floatingForn">Fornecedores</label>
            </div>
        </div>
        <div class="row g-3 d-flex justify-content-center">
            <div class="btn-group btn-group-lg col-md-8" role="group" aria-label="Ações de cancelar e cadastrar">
                <a class="btn btn-danger" href="{% url 'produtos:categoria-excluir' categoria.id %}"><b>Excluir</b></a>
                <a class="btn btn-secondary" href="{% url 'produtos:categoria-listar' %}">Cancelar</a>
                <button type="submit" class="btn btn-primary">Atualizar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

produtos/templates/produtos/categoria_form.html
{% extends 'base.html' %}

{% block title %}Registrar Categoria{% endblock %}

{% block content %}


<div class="container col-lg-7 p-2">

    <div>
        <h1 class="p-2">Cadastrar Categoria</h1>
    </div>

    <form method="POST">{% csrf_token %}
        <div class="row g-3">
            <div class="form-floating mb-3 col-md-6">
                {{ form.nome }}
                <label for="floatingNome">Nome</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.fornecedores }}
                <label for="floatingForn">Fornecedores</label>
            </div>
        </div>
        <div class="row g-3 d-flex justify-content-center">
            <div class="btn-group btn-group-lg col-md-8" role="group" aria-label="Ações de cancelar e cadastrar">
                <a class="btn btn-danger" href="{% url 'produtos:categoria-listar' %}">Cancelar</a>
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

produtos/templates/produtos/categoria_list.html
{% extends 'base.html' %}

{% block title %}Categorias{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Categorias</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="#">Ordenar</a>
        <a class="nav-link" href="#">Quantidade</a>
      </div>
    <form class="d-flex">
     <input class="form-control me-2" type="search" placeholder="Localizar" aria-label="Localizar">
     <div class="d-grid gap-2 d-flex justify-content-end">
         <button class="btn btn-success" type="submit">OK</button>
         <a class="btn btn-primary" href="{% url 'produtos:categoria-registrar' %}">Novo</a>
     </div>
    </form> 
    </div>

  </div>
</nav>
    <div class="table-responsive">
        <table class="table table-sm table-striped table-hover table-bordered">
            <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Fornecedores</th>
                </tr>
            </thead>
            <tbody>
                {% for produto in object_list %}
                <tr onclick="document.location = '{{ categoria.get_absolute_url }}';">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ marca.nome|upper }}</td>
                    <td>{{ marca.fornecedores|upper }}</td>
                </tr>
                {% empty %}
                    <li>Não existem categorias cadastradas.</li>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

produtos/templates/produtos/marca_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Deletar marca {{ marca.nome }}{% endblock %}

{% block content %}


<form method="POST">{% csrf_token %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Deseja excluir {{ marca.nome }}?</h4>
        <p>Cuidado! Ao excluir um item ele não poderá ser recuperado e terá que ser cadastrado novamente</p>
        <hr>
        <p class="mb-0">Clique em <strong>confirmar</strong> para excluir a Marca.</p>
    </div>
    <input type="submit" class="btn btn-danger" value="Confirmar">
</form>

{% endblock %}

produtos/templates/produtos/marca_detail.html
{% extends 'base.html' %}

{% block title %}{{ marca.nome }}{% endblock %}

{% block content %}


<div class="container col-lg-7 p-2">

    <div>
        <h1 class="p-2">Detalhes e atualização</h1>
    </div>

    <form action="{% url 'categoria:detalhes' categoria.id %}" method="POST">{% csrf_token %}
        <div class="row g-3">
            <div class="form-floating mb-3 col-md-6">
                {{ form.nome }}
                <label for="floatingNome">Nome</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.categoria }}
                <label for="floatingForn">Categoria</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.fornecedores }}
                <label for="floatingForn">Fornecedores</label>
            </div>
        </div>
        <div class="row g-3 d-flex justify-content-center">
            <div class="btn-group btn-group-lg col-md-8" role="group" aria-label="Ações de cancelar e cadastrar">
                <a class="btn btn-danger" href="{% url 'produtos:marca-excluir' marca.id %}"><b>Excluir</b></a>
                <a class="btn btn-secondary" href="{% url 'produtos:marca-listar' %}">Cancelar</a>
                <button type="submit" class="btn btn-primary">Atualizar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

produtos/templates/produtos/marca_form.html
{% extends 'base.html' %}

{% block title %}Registrar Marca{% endblock %}

{% block content %}


<div class="container col-lg-7 p-2">

    <div>
        <h1 class="p-2">Registrar Marca</h1>
    </div>

    <form method="POST">{% csrf_token %}
        <div class="row g-3">
            <div class="form-floating mb-3 col-md-6">
                {{ form.nome }}
                <label for="floatingNome">Nome</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.categoria }}
                <label for="floatingForn">Categoria</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.fornecedores }}
                <label for="floatingForn">Fornecedores</label>
            </div>
        </div>
        <div class="row g-3 d-flex justify-content-center">
            <div class="btn-group btn-group-lg col-md-8" role="group" aria-label="Ações de cancelar e cadastrar">
                <a class="btn btn-danger" href="{% url 'produtos:marca-listar' %}">Cancelar</a>
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

produtos/templates/produtos/marca_list.html
{% extends 'base.html' %}

{% block title %}Marcas{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Marcas</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="#">Ordenar</a>
        <a class="nav-link" href="#">Quantidade</a>
      </div>
    <form class="d-flex">
     <input class="form-control me-2" type="search" placeholder="Localizar" aria-label="Localizar">
     <div class="d-grid gap-2 d-flex justify-content-end">
         <button class="btn btn-success" type="submit">OK</button>
         <a class="btn btn-primary" href="{% url 'produtos:marca-registrar' %}">Novo</a>
     </div>
    </form> 
    </div>

  </div>
</nav>
    <div class="table-responsive">
        <table class="table table-sm table-striped table-hover table-bordered">
            <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Categoria</th>
                    <th scope="col">Fornecedores</th>
                </tr>
            </thead>
            <tbody>
                {% for produto in object_list %}
                <tr onclick="document.location = '{{ marca.get_absolute_url }}';">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ produto.nome|upper }}</td>
                    <td>{{ marca.categoria|upper }}</td>
                    <td>{{ marca.fornecedores|upper }}</td>
                </tr>
                {% empty %}
                    <li>Não existem marcas cadastradas.</li>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}

produtos/templates/produtos/produto_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Deletar produto {{ produto.nome }}{% endblock %}

{% block content %}


<form method="POST">{% csrf_token %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Deseja excluir {{ produto.nome }}?</h4>
        <p>Cuidado! Ao excluir um item ele não poderá ser recuperado e terá que ser cadastrado novamente</p>
        <hr>
        <p class="mb-0">Clique em <strong>confirmar</strong> para excluir o Produto.</p>
    </div>
    <input type="submit" class="btn btn-danger" value="Confirmar">
</form>

{% endblock %}

produtos/templates/produtos/produto_detail.html
{% extends 'base.html' %}

{% block title %}{{ produto.nome }}{% endblock %}

{% block content %}


<div class="container col-lg-7 p-2">

    <div>
        <h1 class="p-2">Detalhes e atualização</h1>
    </div>

    <form action="{% url 'produtos:detalhes' produto.id %}" method="POST">{% csrf_token %}
        <div class="row g-3">
            <div class="form-check form-switch mb-3 col-md-12">
                {{ form.disponivel }}
                <label class="form-check-label" for="flexSwDisp">Disponível</label>
            </div>
            <div class="form-floating mb-3 col-md-6">
                {{ form.codigo_barras }}
                <label for="floatingBarras">Código de barras</label>
            </div>
            <div class="form-floating mb-3 col-md-6">
                {{ form.nome }}
                <label for="floatingNome">Nome</label>
            </div>
            <div class="form-floating mb-3 col-12">
                {{ form.descricacao }}
                <label for="floatingDesc">Descrição</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.custo }}
                <label for="floatingCusto">Custo</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.preco }}
                <label for="floatingPreco">Preço</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.categoria }}
                <label for="floatingCate">Categoria</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.marca }}
                <label for="floatingMarca">Marca</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.fornecedor }}
                <label for="floatingForn">Fornecedor</label>
            </div>
        </div>
        <div class="row g-3 d-flex justify-content-center">
            <div class="btn-group btn-group-lg col-md-8" role="group" aria-label="Ações de cancelar e cadastrar">
                <a class="btn btn-danger" href="{% url 'produtos:excluir' produto.id %}"><b>Excluir</b></a>
                <a class="btn btn-secondary" href="{% url 'produtos:listar' %}">Cancelar</a>
                <button type="submit" class="btn btn-primary">Atualizar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

produtos/templates/produtos/produto_form.html
{% extends 'base.html' %}

{% block title %}Registrar Produtos{% endblock %}

{% block content %}


<div class="container col-lg-7 p-2">

    <div>
        <h1 class="p-2">Cadastrar Produto</h1>
    </div>

    <form method="POST">{% csrf_token %}
        <div class="row g-3">
            <div class="form-check form-switch mb-3 col-md-12">
                {{ form.disponivel }}
                <label class="form-check-label" for="flexSwDisp">Disponível</label>
            </div>
            <div class="form-floating mb-3 col-md-6">
                {{ form.codigo_barras }}
                <label for="floatingBarras">Código de barras</label>
            </div>
            <div class="form-floating mb-3 col-md-6">
                {{ form.nome }}
                <label for="floatingNome">Nome</label>
            </div>
            <div class="form-floating mb-3 col-12">
                {{ form.descricacao }}
                <label for="floatingDesc">Descrição</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.custo }}
                <label for="floatingCusto">Custo</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.preco }}
                <label for="floatingPreco">Preço</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.categoria }}
                <label for="floatingCate">Categoria</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.marca }}
                <label for="floatingMarca">Marca</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.fornecedores }}
                <label for="floatingForn">Fornecedores</label>
            </div>
        </div>
        <div class="row g-3 d-flex justify-content-center">
            <div class="btn-group btn-group-lg col-md-8" role="group" aria-label="Ações de cancelar e cadastrar">
                <a class="btn btn-danger" href="{% url 'produtos:listar' %}">Cancelar</a>
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

produtos/templates/produtos/produto_list.html
{% extends 'base.html' %}

{% block title %}Produtos{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Produtos</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="#">Ordenar</a>
        <a class="nav-link" href="#">Quantidade</a>
      </div>
    <form class="d-flex">
     <input class="form-control me-2" type="search" placeholder="Localizar" aria-label="Localizar">
     <div class="d-grid gap-2 d-flex justify-content-end">
         <button class="btn btn-success" type="submit">OK</button>
         <a class="btn btn-primary" href="{% url 'produtos:registrar' %}">Novo</a>
     </div>
    </form> 
    </div>

  </div>
</nav>
    <div class="table-responsive">
        <table class="table table-sm table-striped table-hover table-bordered">
            <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Barras</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Custo</th>
                    <th scope="col">Preço (R$)</th>
                    <th scope="col">Atualizado</th>
                    <th scope="col">Disponível</th>
                </tr>
            </thead>
            <tbody>
                {% for produto in object_list %}
                <tr onclick="document.location = '{{ produto.get_absolute_url }}';">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ produto.codigo_barras }}</td>
                    <td>{{ produto.nome|upper }}</td>
                    <td>{{ produto.custo }}</td>
                    <td>{{ produto.preco }}</td>
                    <td>{{ produto.atualizado }}</td>
                    <td>{{ produto.disponivel }}</td>
                </tr>
                {% empty %}
                    <li>Não existem produtos cadastrados.</li>
                {% endfor %}
            </tbody>
        </table>
    </div>


{% endblock %}