jbc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('core.urls')),
    path('produtos/', include('produtos.urls')),
    path('clientes-e-fornecedores/', include('pessoas.urls')),
]

pessoas/urls.py
from django.urls import path

from produtos import views
from . import views

app_name = 'pessoas'
urlpatterns = [
    # Cliente
    path('listar-clientes/', views.ClienteList.as_view(), name='listar-clientes'),
    path('registrar-cliente/', views.ClienteCreate.as_view(), name='registrar-cliente'),
    path('detalhe-cliente/<int:pk>/', views.ClienteDetail.as_view(), name='detalhe-cliente'),
    path('detalhe-cliente/<int:pk>/excluir/', views.ClienteRemove.as_view(), name='remover-cliente'),
    # Fornecedor
    path('listar-fornecedores/', views.FornecedorList.as_view(), name='listar-fornecedores'),
    path('registrar-fornecedor/', views.FornecedorCreate.as_view(), name='registrar-fornecedor'),
    path('detalhe-fornecedor/<int:pk>/', views.FornecedorDetail.as_view(), name='detalhe-fornecedor'),
    path('detalhe-fornecedor/<int:pk>/excluir/', views.FornecedorRemove.as_view(), name='remover-fornecedor'),
    ]

pessoas/models.py
from django.db import models
from django.utils import timezone

class DadosGerais(models.Model):
    endereco = models.CharField(max_length=30)
    endereco_numero = models.CharField(max_length=6)
    endereco_complemento = models.CharField(max_length=35,
                                            blank=True,
                                            null=True)
    cidade = models.CharField(max_length=20)
    estado = models.CharField(max_length=20)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class PessoaFisica(models.Model):
    nome_completo = models.CharField(max_length=80)
    apelido = models.CharField(max_length=15,
                               null=True)
    cpf = models.CharField(max_length=15,
                           unique=True,
                           db_index=True)
    rg = models.CharField(max_length=15,
                          unique=True,
                          db_index=True)
    nascimento = models.DateField(null=True)
    
    class Meta:
        abstract = True


class PessoaJuridica(models.Model):
    razao_social = models.CharField(max_length=80)
    nome_fantasia = models.CharField(max_length=80)
    cnpj = models.CharField(max_length=16)

    class Meta:
        abstract = True


class Cliente(PessoaFisica, PessoaJuridica, DadosGerais):
    TIPO_CLIENTE_CHOICES = [
        ('F', 'Física'),
        ('J', 'Jurídica'),
    ]
    tipo_cliente = models.CharField(max_length=8,
                                    choices=TIPO_CLIENTE_CHOICES,
                                    default='F')
    limite_fiado = models.DecimalField(max_digits=7,
                                       decimal_places=2,
                                       null=True)

    class Meta(PessoaFisica.Meta, PessoaJuridica.Meta, DadosGerais.Meta):
        pass

    def __str__(self):
        return self.nome_completo, self.nome_fantasia


class Fornecedor(PessoaJuridica, PessoaFisica, DadosGerais):
    TIPO_FORNECEDOR_CHOICES = [
        ('F', 'Física'),
        ('J', 'Jurídica'),
    ]
    tipo_fornecedor = models.CharField(max_length=8,
                                       choices=TIPO_FORNECEDOR_CHOICES,
                                       default='J')
    class Meta(PessoaFisica.Meta, PessoaJuridica.Meta, DadosGerais.Meta):
        pass

    def __str__(self):
        return self.nome_completo, self.nome_fantasia

pessoas/forms.py
from django.forms import ModelForm, widgets, DateInput
from .models import Cliente, Fornecedor

class RegistroClienteForm(ModelForm):
    class Meta:
        model = Cliente
        exclude = ('slug',)
        widgets = {
            'nome_completo': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Nome completo',
                'id': 'floatingNomeCompleto',
                'required': '',
            }),
            'apelido': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Apelido',
                'id': 'floatingApelido',
            }),
            'cpf': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'CPF',
                'id': 'floatingCPF',
            }),
            'rg': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'RG',
                'id': 'floatingRG',
            }),
            'nascimento': widgets.DateInput(format="%d/%m/%y", attrs={
                'type': 'date',
                'class': 'form-control',
                'placeholder': 'Nascimento dd/mm/aaaa',
                'id': 'floatingNascimento',
            }),
            'razao_social': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Razão Social',
                'id': 'floatingRSocial',
            }),
            'nome_fantasia': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Nome Fantasia',
                'id': 'floatingNFantasia',
            }),
            'cnpj': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'CNPJ',
                'id': 'floatingCNPJ',
            }),
            'endereco': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Endereço',
                'id': 'floatingEndereco',
            }),
            'endereco_numero': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Número',
                'id': 'floatingNumero',
            }),
            'endereco_complemento': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Complemento',
                'id': 'floatingComplemento',
            }),
            'cidade': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Cidade',
                'id': 'floatingCidade',
            }),
            'estado': widgets.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Estado',
                'id': 'floatingEstado',
            }),
            'limite_fiado': widgets.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Limite',
                'id': 'floatingLimite',
            })
        }


class RegistroFornecedorForm(ModelForm):
    class Meta:
       model = Fornecedor
       exclude = ('slug',)
       widgets = {
           'nome_completo': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Nome completo',
               'id': 'floatingNomeCompleto',
               'required': '',
           }),
           'apelido': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Apelido',
               'id': 'floatingApelido',
           }),
           'cpf': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'CPF',
               'id': 'floatingCPF',
           }),
           'rg': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'RG',
               'id': 'floatingRG',
           }),
           'nascimento': widgets.DateInput(format="%d/%m/%y", attrs={
               'type': 'date',
               'class': 'form-control',
               'placeholder': 'Nascimento dd/mm/aaaa',
               'id': 'floatingNascimento',
           }),
           'razao_social': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Razão Social',
               'id': 'floatingRSocial',
           }),
           'nome_fantasia': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Nome Fantasia',
               'id': 'floatingNFantasia',
           }),
           'cnpj': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'CNPJ',
               'id': 'floatingCNPJ',
           }),
           'endereco': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Endereço',
               'id': 'floatingEndereco',
           }),
           'endereco_numero': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Número',
               'id': 'floatingNumero',
           }),
           'endereco_complemento': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Complemento',
               'id': 'floatingComplemento',
           }),
           'cidade': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Cidade',
               'id': 'floatingCidade',
           }),
           'estado': widgets.Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Estado',
               'id': 'floatingEstado',
           }),
           'limite_fiado': widgets.NumberInput(attrs={
               'class': 'form-control',
               'placeholder': 'Limite',
               'id': 'floatingLimite',
           })
       }

pessoas/views.py
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.views.generic.list import ListView

from .forms import RegistroClienteForm, RegistroFornecedorForm
from .models import Cliente, Fornecedor

# CLIENTE
class ClienteList(LoginRequiredMixin, ListView):
    model = Cliente
    paginate_by = 50


class ClienteCreate(LoginRequiredMixin, CreateView):
    template_name = 'pessoas/cliente_form.html'
    model = Cliente
    form_class = RegistroClienteForm
    success_url = reverse_lazy('pessoas:listar-clientes')


class ClienteDetail(LoginRequiredMixin, UpdateView):
    model = Cliente
    template_name = 'pessoas/cliente_detail.html'
    form_class = RegistroClienteForm
    success_url = reverse_lazy('pessoas:listar-clientes')


class ClienteRemove(LoginRequiredMixin, DeleteView):
    model = Cliente
    success_url = reverse_lazy('pessoas:listar-clientes')


# FORNECEDOR
class FornecedorList(LoginRequiredMixin, ListView):
    model = Fornecedor
    paginate_by = 50


class FornecedorCreate(LoginRequiredMixin, CreateView):
    template_name = 'pessoas/fornecedor_form.html'
    model = Fornecedor
    form_class = RegistroFornecedorForm
    success_url = reverse_lazy('pessoas:listar-fornecedores')


class FornecedorDetail(LoginRequiredMixin, UpdateView):
    model = Fornecedor
    template_name = 'pessoas/fornecedor_detail.html'
    form_class = RegistroFornecedorForm
    success_url = reverse_lazy('pessoas:listar-fornecedores')


class FornecedorRemove(LoginRequiredMixin, DeleteView):
    model = Fornecedor
    success_url = reverse_lazy('pessoas:listar-fornecedores')

pessoas/templates/pessoas/cliente_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Excluir Cliente {{ cliente.nome }}{% endblock %}

{% block content %}


<form method="POST">{% csrf_token %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Deseja excluir {{ cliente.nome }}?</h4>
        <p>Cuidado! Ao excluir um item ele não poderá ser recuperado e terá que ser cadastrado novamente</p>
        <hr>
        <p class="mb-0">Clique em <strong>confirmar</strong> para excluir o Cliente.</p>
    </div>
    <input type="submit" class="btn btn-danger" value="Confirmar">
</form>

{% endblock %}

pessoas/templates/pessoas/cliente_detail.html
{% extends 'base.html' %}

{% block title %}{{ cliente.nome }}{% endblock %}

{% block content %}


<div class="container col-lg-7 p-2">

    <div>
        <h1 class="p-2">Detalhes e atualização</h1>
    </div>

    <form action="{% url 'pessoas:detalhe-cliente' cliente.id %}" method="POST">{% csrf_token %}
        <div class="row g-3">
            <div class="form-check">
                <input class="form-check-input" for="{{ tipo_cliente }}" type="radio" name="flexRadioDefault" value="F" id="F" onchange="displayFields(this.value)" />
                <label class="form-check-label" for="F">
                    Física
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" for="{{ tipo_cliente }}" type="radio" name="flexRadioDefault" value="J" id="J" onchange="displayFields(this.value)" />
                <label class="form-check-label" for="J">
                    Jurídica
                </label>
            </div>
            <div id="pessoaF" style="display: none;">
                <div class="form-floating mb-3 col-md-9">
                    {{ form.cpf }}
                    <label for="floatingCPF">CPF</label>
                </div>
                <div class="form-floating mb-3 col-md-12">
                    {{ form.nome_completo }}
                    <label for="floatingNomeCompleto">Nome Completo</label>
                </div>
                <div class="form-floating mb-3 col-md-6">
                    {{ form.apelido }}
                    <label for="floatingApelido">Apelido</label>
                </div>
                <div class="form-floating mb-3 col-md-6">
                    {{ form.rg }}
                    <label for="floatingRG">RG</label>
                </div>
                <div class="form-floating mb-3 col-md-6">
                    {{ form.nascimento }}
                    <label for="floatingNascimento">Nascimento</label>
                </div>
            </div>
            <div id="pessoaJ" style="display: none;">
                <div class="form-floating mb-3 col-md-9">
                    {{ form.cnpj }}
                    <label for="floatingCNPJ">CNPJ</label>
                </div>
                <div class="form-floating mb-3 col-md-12">
                    {{ form.razao_social }}
                    <label for="floatingRSocial">Razão Social</label>
                </div>
                <div class="form-floating mb-3 col-md-12">
                    {{ form.nome_fantasia }}
                    <label for="floatingNFantasia">Nome Fantasia</label>
                </div>
            </div>
            <div class="form-floating mb-3 col-md-9">
                {{ form.endereco }}
                <label for="floatingEndereco">Endereço</label>
            </div>
            <div class="form-floating mb-3 col-md-3">
                {{ form.endereco_numero }}
                <label for="floatingNumero">Número</label>
            </div>
            <div class="form-floating mb-3 col-md-12">
                {{ form.endereco_complemento }}
                <label for="floatingComplento">Complemento</label>
            </div>
            <div class="form-floating mb-3 col-md-8">
                {{ form.cidade }}
                <label for="floatingCidade">Cidade</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.estado }}
                <label for="floatingEstado">Estado</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.limite_fiado }}
                <label for="floatingLimite">Limite</label>
            </div>
        </div>
        <div class="row g-3 d-flex justify-content-center">
            <div class="btn-group btn-group-lg col-md-8" role="group" aria-label="Ações de cancelar e cadastrar">
                <a class="btn btn-danger" href="{% url 'pessoas:excluir-cliente' cliente.id %}"><b>Excluir</b></a>
                <a class="btn btn-danger" href="{% url 'pessoas:listar-clientes' %}">Cancelar</a>
                <button type="submit" class="btn btn-primary">Atualizar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

pessoas/templates/pessoas/cliente_form.html
{% extends 'base.html' %}

{% block title %}Registrar Cliente{% endblock %}

{% block content %}

<script>
function displayFields(tipo) {
    var tipoPessoa = document.getElementById('pessoa' + tipo);
    if (tipo == "F") { // hide the div that is not selected
        tipoPessoa.style.display = 'block';
        pessoaJ.style.display = 'none';
    } else if (tipo == "J") {
        tipoPessoa.style.display = 'block';
        pessoaF.style.display = 'none';
    }
}
</script>

<div class="container col-lg-7 p-2">

    <div>
        <h1 class="p-2">Registrar Cliente</h1>
    </div>

    <form method="POST" action="javascript:void(0)">{% csrf_token %}
        <div class="row g-3">
            <div class="form-check">
                <input class="form-check-input" for="{{ tipo_cliente }}" type="radio" name="flexRadioDefault" value="F" id="F" onchange="displayFields(this.value)" />
                <label class="form-check-label" for="F">
                    Física
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" for="{{ tipo_cliente }}" type="radio" name="flexRadioDefault" value="J" id="J" onchange="displayFields(this.value)" />
                <label class="form-check-label" for="J">
                    Jurídica
                </label>
            </div>
            <div id="pessoaF" style="display: none;">
                <div class="form-floating mb-3 col-md-9">
                    {{ form.cpf }}
                    <label for="floatingCPF">CPF</label>
                </div>
                <div class="form-floating mb-3 col-md-12">
                    {{ form.nome_completo }}
                    <label for="floatingNomeCompleto">Nome Completo</label>
                </div>
                <div class="form-floating mb-3 col-md-6">
                    {{ form.apelido }}
                    <label for="floatingApelido">Apelido</label>
                </div>
                <div class="form-floating mb-3 col-md-6">
                    {{ form.rg }}
                    <label for="floatingRG">RG</label>
                </div>
                <div class="form-floating mb-3 col-md-6">
                    {{ form.nascimento }}
                    <label for="floatingNascimento">Nascimento</label>
                </div>
            </div>
            <div id="pessoaJ" style="display: none;">
                <div class="form-floating mb-3 col-md-9">
                    {{ form.cnpj }}
                    <label for="floatingCNPJ">CNPJ</label>
                </div>
                <div class="form-floating mb-3 col-md-12">
                    {{ form.razao_social }}
                    <label for="floatingRSocial">Razão Social</label>
                </div>
                <div class="form-floating mb-3 col-md-12">
                    {{ form.nome_fantasia }}
                    <label for="floatingNFantasia">Nome Fantasia</label>
                </div>
            </div>
            <div class="form-floating mb-3 col-md-9">
                {{ form.endereco }}
                <label for="floatingEndereco">Endereço</label>
            </div>
            <div class="form-floating mb-3 col-md-3">
                {{ form.endereco_numero }}
                <label for="floatingNumero">Número</label>
            </div>
            <div class="form-floating mb-3 col-md-12">
                {{ form.endereco_complemento }}
                <label for="floatingComplento">Complemento</label>
            </div>
            <div class="form-floating mb-3 col-md-8">
                {{ form.cidade }}
                <label for="floatingCidade">Cidade</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.estado }}
                <label for="floatingEstado">Estado</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.limite_fiado }}
                <label for="floatingLimite">Limite</label>
            </div>
        </div>
        <div class="row g-3 d-flex justify-content-center">
            <div class="btn-group btn-group-lg col-md-8" role="group" aria-label="Ações de cancelar e cadastrar">
                <a class="btn btn-danger" href="{% url 'pessoas:listar-clientes' %}">Cancelar</a>
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

pessoas/templates/pessoas/cliente_list.html
{% extends 'base.html' %}

{% block title %}Clientes{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Clientes</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="#">Ordenar</a>
        <a class="nav-link" href="#">Quantidade</a>
      </div>
    <form class="d-flex">
     <input class="form-control me-2" type="search" placeholder="Localizar" aria-label="Localizar">
     <div class="d-grid gap-2 d-flex justify-content-end">
        <button class="btn btn-success" type="submit">OK</button>
        <a class="btn btn-primary" href="{% url 'pessoas:registrar-cliente' %}">Novo</a>
     </div>
    </form> 
    </div>

  </div>
</nav>
    <div class="table-responsive">
        <table class="table table-sm table-striped table-hover table-bordered">
            <thead class="table-dark">
                <tr>
                    <th scope="col">#</th>
                    {% if cliente.tipo_cliente == 'F' %}
                        <th scope="col">Nome</th>
                        <th scope="col">Apelido</th>
                        <th scope="col">CPF</th>
                    {% else %}
                        <th scope="col">Razão Social</th>
                        <th scope="col">Nome Fantasia</th>
                        <th scope="col">CNPJ</th>
                    {% endif %}
                    <th scope="col">Atualizado</th>
                </tr>
            </thead>
            <tbody>
                {% for produto in object_list %}
                <tr onclick="document.location = '{{ cliente.get_absolute_url }}';">
                    <td>{{ forloop.counter }}</td>
                    {% if cliente.tipo_cliente == 'F' %}
                        <td>{{ cliente.nome|upper }}</td>
                        <td>{{ cliente.apelido|upper }}</td>
                        <td>{{ cliente.cpf }}</td>
                    {% else %}
                        <td>{{ cliente.razao_social }}</td>
                        <td>{{ cliente.nome_fantasia }}</td>
                        <td>{{ cliente.cnpj }}</td>
                    {% endif %}
                    <td>{{ cliente.atualizado }}</td>
                </tr>
                {% empty %}
                    <li>Não existem produtos cadastrados.</li>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

pessoas/templates/pessoas/fornecedor_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Deletar produto {{ fornecedor.nome }}{% endblock %}

{% block content %}


<form method="POST">{% csrf_token %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Deseja excluir {{ fornecedor.nome }}?</h4>
        <p>Cuidado! Ao excluir um item ele não poderá ser recuperado e terá que ser cadastrado novamente</p>
        <hr>
        <p class="mb-0">Clique em <strong>confirmar</strong> para excluir o Fornecedor.</p>
    </div>
    <input type="submit" class="btn btn-danger" value="Confirmar">
</form>

{% endblock %}

pessoas/templates/pessoas/fornecedor_detail.html
{% extends 'base.html' %}

{% block title %}{{ fornecedor.nome }}{% endblock %}

{% block content %}


<div class="container col-lg-7 p-2">

    <div>
        <h1 class="p-2">Detalhes e atualização</h1>
    </div>

    <form action="{% url 'pessoas:detalhe-fornecedor' fornecedor.id %}" method="POST">{% csrf_token %}
        <div class="row g-3">
            <div class="form-check">
                <input class="form-check-input" for="{{ tipo_cliente }}" type="radio" name="flexRadioDefault" value="F" id="F" onchange="displayFields(this.value)" />
                <label class="form-check-label" for="F">
                    Física
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" for="{{ tipo_cliente }}" type="radio" name="flexRadioDefault" value="J" id="J" onchange="displayFields(this.value)" />
                <label class="form-check-label" for="J">
                    Jurídica
                </label>
            </div>
            <div id="pessoaF" style="display: none;">
                <div class="form-floating mb-3 col-md-9">
                    {{ form.cpf }}
                    <label for="floatingCPF">CPF</label>
                </div>
                <div class="form-floating mb-3 col-md-12">
                    {{ form.nome_completo }}
                    <label for="floatingNomeCompleto">Nome Completo</label>
                </div>
                <div class="form-floating mb-3 col-md-6">
                    {{ form.apelido }}
                    <label for="floatingApelido">Apelido</label>
                </div>
                <div class="form-floating mb-3 col-md-6">
                    {{ form.rg }}
                    <label for="floatingRG">RG</label>
                </div>
                <div class="form-floating mb-3 col-md-6">
                    {{ form.nascimento }}
                    <label for="floatingNascimento">Nascimento</label>
                </div>
            </div>
            <div id="pessoaJ" style="display: none;">
                <div class="form-floating mb-3 col-md-9">
                    {{ form.cnpj }}
                    <label for="floatingCNPJ">CNPJ</label>
                </div>
                <div class="form-floating mb-3 col-md-12">
                    {{ form.razao_social }}
                    <label for="floatingRSocial">Razão Social</label>
                </div>
                <div class="form-floating mb-3 col-md-12">
                    {{ form.nome_fantasia }}
                    <label for="floatingNFantasia">Nome Fantasia</label>
                </div>
            </div>
            <div class="form-floating mb-3 col-md-9">
                {{ form.endereco }}
                <label for="floatingEndereco">Endereço</label>
            </div>
            <div class="form-floating mb-3 col-md-3">
                {{ form.endereco_numero }}
                <label for="floatingNumero">Número</label>
            </div>
            <div class="form-floating mb-3 col-md-12">
                {{ form.endereco_complemento }}
                <label for="floatingComplento">Complemento</label>
            </div>
            <div class="form-floating mb-3 col-md-8">
                {{ form.cidade }}
                <label for="floatingCidade">Cidade</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.estado }}
                <label for="floatingEstado">Estado</label>
            </div>
            <div class="form-floating mb-3 col-md-4">
                {{ form.limite_fiado }}
                <label for="floatingLimite">Limite</label>
            </div>
        </div>
        <div class="row g-3 d-flex justify-content-center">
            <div class="btn-group btn-group-lg col-md-8" role="group" aria-label="Ações de cancelar e cadastrar">
                <a class="btn btn-danger" href="{% url 'pessoas:excluir-fornecedor' fornecedor.id %}"><b>Excluir</b></a>
                <a class="btn btn-danger" href="{% url 'pessoas:listar-fornecedor' %}">Cancelar</a>
                <button type="submit" class="btn btn-primary">Atualizar</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

pessoas/templates/pessoas/fornecedor_list.html
{% extends 'base.html' %}

{% block title %}Fornecedores{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Fornecedores</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="#">Ordenar</a>
        <a class="nav-link" href="#">Quantidade</a>
      </div>
    <form class="d-flex">
     <input class="form-control me-2" type="search" placeholder="Localizar" aria-label="Localizar">
     <div class="d-grid gap-2 d-flex justify-content-end">
        <button class="btn btn-success" type="submit">OK</button>
        <a class="btn btn-primary" href="{% url 'pessoas:registrar-fornecedor' %}">Novo</a>
     </div>
    </form> 
    </div>

  </div>
</nav>
    <div class="table-responsive">
        <table class="table table-sm table-striped table-hover table-bordered">
            <thead class="table-dark">
                <tr>
                {% if cliente.tipo_cliente == 'F' %}
                    <th scope="col">Nome</th>
                    <th scope="col">Apelido</th>
                    <th scope="col">CPF</th>
                {% else %}
                    <th scope="col">Razão Social</th>
                    <th scope="col">Nome Fantasia</th>
                    <th scope="col">CNPJ</th>
                {% endif %}
                    <th scope="col">Atualizado</th>
                </tr>
            </thead>
            <tbody>
                {% for produto in object_list %}
                <tr onclick="document.location = '{{ fornecedor.get_absolute_url }}';">
                    <td>{{ forloop.counter }}</td>
                    {% if cliente.tipo_cliente == 'F' %}
                        <td>{{ fornecedor.razao_social|upper }}</td>
                        <td>{{ fornecedor.nome_fantasia|upper }}</td>
                        <td>{{ fornecedor.cnpj }}</td>
                    {% else %}
                        <td>{{ cliente.razao_social }}</td>
                        <td>{{ cliente.nome_fantasia }}</td>
                        <td>{{ cliente.cnpj }}</td>
                    {% endif %}
                    <td>{{ fornecedor.atualizado }}</td>
                </tr>
                {% empty %}
                    <li>Não existem produtos cadastrados.</li>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}