core/urls.py
from django.urls import path
from core.views import AplicativosView

app_name = 'core'
urlpatterns = [
    path('aplicativos/', AplicativosView.as_view(), name='aplicativos'),
]

jbc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('core.urls')),
    path('produtos/', include('produtos.urls')),
    path('clientes-e-fornecedores/', include('pessoas.urls')),
]

pessoas/urls.py
from django.urls import path

from produtos import views
from . import views

app_name = 'pessoas'
urlpatterns = [
    # Cliente
    path('listar-clientes/', views.ClienteList.as_view(), name='listar-clientes'),
    path('registrar-cliente/', views.ClienteCreate.as_view(), name='registrar-cliente'),
    path('detalhe-cliente/<int:pk>/', views.ClienteDetail.as_view(), name='detalhe-cliente'),
    path('detalhe-cliente/<int:pk>/excluir/', views.ClienteRemove.as_view(), name='remover-cliente'),
    # Fornecedor
    path('listar-fornecedores/', views.FornecedorList.as_view(), name='listar-fornecedores'),
    path('registrar-fornecedor/', views.FornecedorCreate.as_view(), name='registrar-fornecedor'),
    path('detalhe-fornecedor/<int:pk>/', views.FornecedorDetail.as_view(), name='detalhe-fornecedor'),
    path('detalhe-fornecedor/<int:pk>/excluir/', views.FornecedorRemove.as_view(), name='remover-fornecedor'),
    ]

produtos/urls.py
from django.urls import path
from . import views

app_name = 'produtos'
urlpatterns = [
    path('', views.ProdutosList.as_view(), name='listar'),
    path('registrar/', views.ProdutosCreate.as_view(), name='registrar'),
    path('detalhes/<int:pk>/', views.ProdutoDetail.as_view(), name='detalhes'),
    path('detalhes/<int:pk>/excluir/', views.ProdutoRemove.as_view(), name='excluir'),
    #categoria
    path('categoria/', views.CategoriaList.as_view(), name='categoria-listar'),
    path('categoria-registrar/', views.CategoriaCreate.as_view(), name='categoria-registrar'),
    path('categoria-detalhes/<int:pk>/', views.CategoriaDetail.as_view(), name='categoria-detalhes'),
    path('categoria-detalhes/<int:pk>/excluir/', views.CategoriaRemove.as_view(), name='categoria-remover'),
    #marca
    path('marca/', views.MarcaList.as_view(), name='marca-listar'),
    path('marca-registrar/', views.MarcaCreate.as_view(), name='marca-registrar'),
    path('marca-detalhes/<int:pk>/', views.MarcaDetail.as_view(), name='marca-detalhes'),
    path('marca-detalhes/<int:pk>/excluir/', views.MarcaRemove.as_view(), name='marca-remover'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class AplicativosView(LoginRequiredMixin, TemplateView):
    template_name = "core/index.html"

core/templates/core/index.html
{% extends "base.html" %}

{% block title %}Aplicativos{% endblock %}

{% block content %}
<div class="container-fluid col-lg-8">
    <div class="alert alert-secondary" role="alert">
        <h5 style="text-align: center;">{% now "l, j F Y" %}</h5>
        <h3 style="text-align: center;">{% now "G:i" %}</h3>
    </div>

    <div class="row">
        <div class="data-hora d-flex justify-content-center p-2">
        </div>
    </div>

    <div class="row">

        <div class="col apps-titulo d-flex justify-content-center">
            <h2>Aplicativos</h2>
        </div>

    </div>

    <div class="row">
        <div class="col d-flex justify-content-center flex-wrap aplicativos">

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location='login.html';">
                    <img src="/static/img/pdv_icon.png" width="100px" height="100px" alt="Ponto de Vendas">
                    <figcaption>Ponto de Vendas</figcaption>
                </div>

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location='login.html';">
                    <img src="/static/img/caixa_icon.png" width="100px" height="100px" alt="Ponto de Vendas">
                    <figcaption>Caixa</figcaption>
                </div>

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location='login.html';">
                    <img src="/static/img/vendas_icon.png" width="100px" height="100px" alt="Ponto de Vendas">
                    <figcaption>Vendas</figcaption>
                </div>

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location='login.html';">
                    <img src="/static/img/entrega_icon.png" width="100px" height="100px" alt="Ponto de Vendas">
                    <figcaption>Entregas</figcaption>
                </div>

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location=`{% url 'produtos:listar' %}`;">
                    <img src="/static/img/produtos_icon.png" width="100px" height="100px" alt="Ponto de Vendas">
                    <figcaption>Produtos</figcaption>
                </div>

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location='login.html';">
                    <img src="/static/img/estoque_icon.png" width="90px" height="90px" alt="Ponto de Vendas">
                    <figcaption>Estoque</figcaption>
                </div>

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location='login.html';">
                    <img src="/static/img/producao_icon.png" width="100px" height="100px" alt="Ponto de Vendas">
                    <figcaption>Produção</figcaption>
                </div>

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location='login.html';">
                    <img src="/static/img/pdv_icon.png" width="100px" height="100px" alt="Ponto de Vendas">
                    <figcaption>Financeiro</figcaption>
                </div>

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location='login.html';">
                    <img src="/static/img/pdv_icon.png" width="100px" height="100px" alt="Ponto de Vendas">
                    <figcaption>Colaboradores</figcaption>
                </div>

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location=`{% url 'pessoas:listar-clientes' %}`;">
                    <img src="/static/img/pdv_icon.png" width="100px" height="100px" alt="Clientes">
                    <figcaption>Clientes</figcaption>
                </div>

                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location=`{% url 'pessoas:listar-fornecedores' %}`;">
                    <img src="/static/img/pdv_icon.png" width="100px" height="100px" alt="Fornecedores">
                    <figcaption>Fornecedores</figcaption>
                </div>
                <div class="col-md-4 btns d-flex justify-content-around align-items-center" style="cursor: pointer;" onclick="window.location='login.html';">
                    <img src="/static/img/cfg_icon.png" width="100px" height="100px" alt="Ponto de Vendas">
                    <figcaption>Configurações</figcaption>
                </div>

            </div>
    </div>

</div>

{% endblock %}