core/urls.py
from django.urls import path
from core.views import AplicativosView

app_name = 'core'
urlpatterns = [
    path('aplicativos/', AplicativosView.as_view(), name='aplicativos'),
]

jbc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('core.urls')),
    path('produtos/', include('produtos.urls')),
    path('clientes-e-fornecedores/', include('pessoas.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark" style="background-color: #3c0435ff;">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'core:aplicativos' %}"><b>Supermercado</b></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'core:aplicativos' %}">Início</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Suporte</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Configurações</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Ajuda</a>
                    </li>
                </ul>
                <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <div class="d-flex btn-group" role="group">
                        {% if request.user.is_authenticated %}
                        <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            Olá, {{ user.first_name }}
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                          <li><a class="dropdown-item" href="/admin/">Admin</a></li>
                          <li><a class="dropdown-item" href="#">Conta</a></li>
                          <li><a class="dropdown-item" href="{% url 'logout' %}">Sair</a></li>
                        </ul>
                        {% else %}
                            <a class="btn btn-primary" href="{% url 'login' %}">Entrar</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav> 

    <div class="container-fluid conteudo d-flex justify-content-center">
        <div class="row conteudo-interior col-12">
            <main class="main">
                {% block content %}
                {% endblock %}
            </main>
        </div>
    </div>

   <div class="container-fluid">
       <div class="row">
           <footer class="footer d-flex justify-content-center align-items-center">
               <img class="logo" src="{% static 'img/logo.png' %}" width="58px" height="58px">
           </footer>
       </div>
   </div>
</body>
</html>